name: Auto Backup index.html

on:
  push:
    paths:
      - 'index.html' # index.html이 업데이트될 때만 실행

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to index_backup.html
        run: cp index.html index_backup.html

      - name: Commit and Push backup
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index_backup.html
          git commit -m "Auto-sync index_backup.html" || exit 0
          git push
